parameters:
#    junior_siteinterne.example.class: Junior\SiteinterneBundle\Example

services:
#    junior_siteinterne.example:
#        class: %junior_siteinterne.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
